import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import TopBar from "./components/Top";
import Footer from "./components/Footer";
import { CartProvider } from "@/app/cartContext";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
      <body>
        <TopBar/>
        <CartProvider>
      <Navbar/>
        {children}
        </CartProvider>
        <Footer/>
      </body>
      
    </html>
    
  );
}
